name: Queue Historic Commits From Bevy Main

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */3 * * *"

env:
  COMMIT_DEPTH: 500

jobs:
  check-queue:
    name: Check Queue
    runs-on: ubuntu-latest
    outputs:
      queue_is_empty: ${{ steps.check_queue.outputs.QUEUE_IS_EMPTY }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "queue"
      - name: Check if queue is empty
        id: check_queue
        run: |
          if [ `ls -1 | wc -l` -eq 0 ]; then
            echo "Queue is empty"
            echo "QUEUE_IS_EMPTY=true" >> "$GITHUB_OUTPUT"
          else
            echo "Queue is not empty"
            echo "QUEUE_IS_EMPTY=false" >> "$GITHUB_OUTPUT"
          fi

  queue-commits:
    needs: [check-queue]
    if: needs.check-queue.outputs.queue_is_empty == 'true'
    name: Queue Commits
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Bevy main branch
        uses: actions/checkout@v4
        with:
          repository: "bevyengine/bevy"
          ref: "main"
          path: "bevy"
          fetch-depth: ${{ env.COMMIT_DEPTH }}
      - uses: actions/checkout@v4
        with:
          ref: "queue"
          path: "queue"
      - uses: actions/checkout@v4
        with:
          ref: "results"
          path: "results"
      - name: Queue historic commits
        id: queue
        run: |
          cd bevy
          i=0
          max=3
          for commit in `git log --no-abbrev-commit --pretty=oneline | sort | cut -d ' ' -f 1 | head -n ${{ env.COMMIT_DEPTH }}`
          do
              if find ../results/ | grep $commit 1> /dev/null 2>&1
              then
                  :
              else
                  i=$((i + 1))
                  touch ../queue/$commit
              fi
              if [ $i -ge $max ]; then
                  break
              fi
          done
          echo "Added $i commits"
          echo "ADDED=$i" >> "$GITHUB_OUTPUT"

      - name: Commit
        if: steps.queue.outputs.ADDED > 0
        run: |
          cd queue
          git config user.name 'Workflow'
          git config user.email '<>'

          git add .
          git commit -m "Queue ${{ steps.queue.outputs.ADDED }} historic commits"
          git push
