name: Queue Commit From Bevy Main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  queue-commit:
    name: Queue Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Bevy main branch
        uses: actions/checkout@v4
        with:
          repository: "bevyengine/bevy"
          ref: "main"
      - uses: actions/checkout@v4
        with:
          ref: "queue"
          path: "queue"
      - name: Queue new commit
        id: env
        run: |
          gitref=`git rev-parse HEAD`
          if ls queue/$gitref 1> /dev/null 2>&1
          then
            echo "commit already queued"
          else
            cd queue
            touch $gitref

            git config user.name 'Workflow'
            git config user.email '<>'

            git add .
            git commit -m "Queue new commit"
            git push
          fi
